language: python
python:
  - "3.6"
install:
  - sudo apt-get install -y libudev-dev
  - pip3 install homeassistant==0.100.3
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
