language: python
python:
  - "3.7"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sed -e '/breaking_changes:/d' -e '/hacs:/,+4d' < configuration.yaml > configuration.yaml
  - sudo apt-get install -y libudev-dev
# added per https://rc.home-assistant.io/integrations/stream#troubleshooting
  - sudo apt-get install -y python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
install:
  - pip3 install homeassistant==0.108.3
  - pip3 install colorlog
script:
#  - hass -c . --script check_config
  - hass -c . --script check_config --info all
