- alias: Welcome Home
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - group.tom_presence
    - group.mitzi_presence
    - group.brandon_presence
    - group.krystle_presence
    from: not_home
    to: home
  action:
#  - delay: 00:00:20
  - service: media_player.alexa_tts
    data_template:
      entity_id: media_player.toms_echo
      message: 'Welcome home {{ trigger.to_state.attributes.friendly_name }}. '

