- alias: Lock Front Doors At Sunset
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
  action:
    service: lock.lock
    entity_id: group.front_locks

- alias: Group is away
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.presence
    to: not_home
  action:
    - service: lock.lock
      entity_id: group.all_locks
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
      data:
        code: !secret alarm_code

- alias: Beep on Door/Window Open/Close
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.doors_windows
  action:
  - service: switch.turn_on
    entity_id: switch.beep_beep

- alias: Trigger monitor.sh departure scan on Door Close
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'on'
    to: 'off'
  action:
  - delay: 00:00:10
  - service: mqtt.publish
    data:
      topic: monitor/scan/DEPART

- alias: Close The Door (2)
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'off'
    to: 'on'
    for:
      minutes: 2
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Please close the door!
  - service: notify.ios_toms_iphone
    data:
      message: Door is open (2)

- alias: Close The Door (10)
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'off'
    to: 'on'
    for:
      minutes: 10
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: A door has been open for ten minutes. Please close the door!
  - service: notify.ios_toms_iphone
    data:
      message: Door is open (10)

- alias: Close The Door (20)
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'off'
    to: 'on'
    for:
      minutes: 20
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Please check all doors. A door has been open for over twenty minutes.
        Please close the door!
  - service: notify.ios_toms_iphone
    data:
      message: Door is open (20)

- alias: Front door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '22:05:00'
  condition:
  - condition: state
    entity_id: lock.front_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the front door is still unlocked!

- alias: Kitchen door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '22:06:00'
  condition:
  - condition: state
    entity_id: lock.kitchen_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the kitchen door is still unlocked!

- alias: Master bedroom door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '22:07:00'
  condition:
  - condition: state
    entity_id: lock.mbr_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the master bedroom door is still unlocked!

- alias: Back door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: lock.back_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the back door is still unlocked!

- alias: Laundry door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '23:59:00'
  condition:
  - condition: state
    entity_id: lock.laundry_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the laundry room door is still unlocked!

- alias: Device State Change Alert
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - group.tom_presence
    - group.mitzi_presence
    - group.brandon_presence
    - group.krystle_presence
  action:
  - service: media_player.alexa_tts
    data_template:
      entity_id: media_player.toms_echo_show
      message: ' {{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state
        == ''home'' %}home{% else %}away{% endif %}. '
  - service: notify.ios_toms_iphone
    data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} is {% if trigger.to_state.state
        == ''home'' %}home{% else %}away{% endif %}. '
      title: ''

- alias: Tom is home
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.tom_home_occupancy_confidence
    above: 10
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: input_boolean.tom_occupancy
  - service: mqtt.publish
    data:
      topic: location/tom
      payload: home

- alias: Mitzi is home
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.mitzi_home_occupancy_confidence
    above: 10
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: input_boolean.mitzi_occupancy
  - service: mqtt.publish
    data:
      topic: location/mitzi
      payload: home

- alias: Brandon is home
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.brandon_home_occupancy_confidence
    above: 10
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: input_boolean.brandon_occupancy
  - service: mqtt.publish
    data:
      topic: location/brandon
      payload: home

- alias: Krystle is home
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.krystle_home_occupancy_confidence
    above: 10
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: input_boolean.krystle_occupancy
  - service: mqtt.publish
    data:
      topic: location/krystle
      payload: home

- alias: Tom is away
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.tom_home_occupancy_confidence
    below: 11
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: input_boolean.tom_occupancy
  - service: mqtt.publish
    data:
      topic: location/tom
      payload: not_home

- alias: Mitzi is away
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.mitzi_home_occupancy_confidence
    below: 11
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: input_boolean.mitzi_occupancy
  - service: mqtt.publish
    data:
      topic: location/mitzi
      payload: not_home

- alias: Brandon is away
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.brandon_home_occupancy_confidence
    below: 11
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: input_boolean.brandon_occupancy
  - service: mqtt.publish
    data:
      topic: location/brandon
      payload: not_home

- alias: Krystle is away
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.krystle_home_occupancy_confidence
    below: 11
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: input_boolean.krystle_occupancy
  - service: mqtt.publish
    data:
      topic: location/krystle
      payload: not_home

- alias: Notify iOS that Front Door is Unlocked
  initial_state: true
  hide_entity: true
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: lock.front_deadbolt_locked
    state: unlocked
  action:
    service: notify.ios_toms_iphone
    data:
      title: Front Door Security Check
      message: It's 10pm and the Front Door is still unlocked.
      data:
        push:
          badge: 0
          category: frontdoorlock

- alias: iOS push action to lock Front Door
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LOCK_FRONTDOOR
  action:
    service: lock.lock
    entity_id: lock.front_deadbolt_locked

- alias: Notify iOS that Kitchen Door is Unlocked
  initial_state: true
  hide_entity: true
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: lock.kitchen_deadbolt_locked
    state: unlocked
  action:
    service: notify.ios_toms_iphone
    data:
      title: Kitchen Door Security Check
      message: It's 10pm and the Kitchen Door is still unlocked.
      data:
        push:
          badge: 0
          category: kitchendoorlock

- alias: iOS push action to lock Kitchen Door
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LOCK_KITCHENDOOR
  action:
    service: lock.lock
    entity_id: lock.kitchen_deadbolt_locked

- alias: Notify iOS that Back Door is Unlocked
  initial_state: true
  hide_entity: true
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: lock.back_deadbolt_locked
    state: unlocked
  action:
    service: notify.ios_toms_iphone
    data:
      title: Back Door Security Check
      message: It's 10pm and the Back Door is still unlocked.
      data:
        push:
          badge: 0
          category: backdoorlock

- alias: iOS push action to lock Back Door
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LOCK_BACKDOOR
  action:
    service: lock.lock
    entity_id: lock.back_deadbolt_locked

- alias: Notify iOS that Laundry Room Door is Unlocked
  initial_state: true
  hide_entity: true
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: lock.laundry_deadbolt_locked
    state: unlocked
  action:
    service: notify.ios_toms_iphone
    data:
      title: Laundry Room Door Security Check
      message: It's 10pm and the Laundry Room Door is still unlocked.
      data:
        push:
          badge: 0
          category: laundrydoorlock

- alias: iOS push action to lock Laundry Room Door
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LOCK_LAUNDRYDOOR
  action:
    service: lock.lock
    entity_id: lock.laundry_deadbolt_locked

- alias: Notify iOS that Master Bedroom Door is Unlocked
  initial_state: true
  hide_entity: true
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: lock.mbr_deadbolt_locked
    state: unlocked
  action:
    service: notify.ios_toms_iphone
    data:
      title: Master Bedroom Door Security Check
      message: It's 10pm and the Master Bedroom Door is still unlocked.
      data:
        push:
          badge: 0
          category: mbrdoorlock

- alias: iOS push action to lock Master Bedroom Door
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LOCK_MBRDOOR
  action:
    service: lock.lock
    entity_id: lock.mbr_deadbolt_locked

- alias: 'Alexa: Lock All Doors'
  initial_state: true
  hide_entity: true
  trigger:
  - entity_id: input_boolean.lock_all_doors
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: group.all_locks
    service: lock.lock
  - data:
      entity_id: input_boolean.lock_all_doors
    service: input_boolean.turn_off

- alias: notify via telegram on Home Assistant start
  initial_state: true
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.telegram_tom
    data:
      message: Home Assistant booted

- alias: notify via telegram to put trash bin out
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '17:00:00'
  condition:
  - condition: time
    weekday: 
      - mon
  - condition: state
    entity_id: group.presence
    state: home
  action:
    service: notify.telegram_group
    data:
      message: Put trash bin out
      data:
        inline_keyboard:
          - '30 Minutes:/30m, 1 Hour:/1h'
          - 'No reminder:/removekeyboard'

- alias: 'Telegram callback to remove keyboard'
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/removekeyboard'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'OK'
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      inline_keyboard: []

- alias: 'Telegram callback to repeat message in 30 minutes'
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/30m'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'OK, reminding you in 30 minutes'
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      inline_keyboard: []
  - delay: '00:30:00'
  - service: notify.telegram_tom
    data_template:
      message: '{{ trigger.event.data.message.text }}'
      data:
        inline_keyboard:
          - '30 Minutes:/30m, 1 Hour:/1h'
          - 'No reminder:/removekeyboard'

- alias: 'Telegram callback to repeat message in 1 hour'
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/1h'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'OK, reminding you in 1 hour'
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      inline_keyboard: []
  - delay: '01:00:00'
  - service: notify.telegram_tom
    data_template:
      message: '{{ trigger.event.data.message.text }}'
      data:
        inline_keyboard:
          - '30 Minutes:/30m, 1 Hour:/1h'
          - 'No reminder:/removekeyboard'
