- alias: notify via telegram on Home Assistant start
  initial_state: true
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.telegram_tom
    data:
      message: Home Assistant booted

- alias: notify via telegram to put trash bin out
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '17:00:00'
  condition:
  - condition: time
    weekday: 
      - mon
  - condition: state
    entity_id: group.presence
    state: home
  action:
    service: notify.telegram_group
    data:
      message: Put trash bin out
      data:
        inline_keyboard:
          - '30 Minutes:/30m, 1 Hour:/1h'
          - 'No reminder:/removekeyboard'

- alias: 'Telegram callback to remove keyboard'
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/removekeyboard'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'OK'
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      inline_keyboard: []

- alias: 'Telegram callback to repeat message in 30 minutes'
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/30m'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'OK, reminding you in 30 minutes'
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      inline_keyboard: []
  - delay: '00:30:00'
  - service: notify.telegram_tom
    data_template:
      message: '{{ trigger.event.data.message.text }}'
      data:
        inline_keyboard:
          - '30 Minutes:/30m, 1 Hour:/1h'
          - 'No reminder:/removekeyboard'

- alias: 'Telegram callback to repeat message in 1 hour'
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/1h'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'OK, reminding you in 1 hour'
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      inline_keyboard: []
  - delay: '01:00:00'
  - service: notify.telegram_tom
    data_template:
      message: '{{ trigger.event.data.message.text }}'
      data:
        inline_keyboard:
          - '30 Minutes:/30m, 1 Hour:/1h'
          - 'No reminder:/removekeyboard'
