homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # https://www.gps-coordinates.net/:
  elevation: 133
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

#=====================
# Includes
#=====================

alarm_control_panel: !include includes/alarm_control_panel.yaml
automation: !include_dir_merge_list automation
cloud: !include includes/cloud.yaml
device_tracker: !include includes/device_tracker.yaml
emulated_hue: !include includes/emulated_hue.yaml
group: !include groups.yaml
input_boolean: !include includes/input_boolean.yaml
ios: !include includes/ios.yaml
konnected: !include includes/konnected.yaml
media_player: !include includes/media_player.yaml
logger: !include includes/logger.yaml
mqtt: !include includes/mqtt.yaml
notify: !include includes/notify.yaml
python_script:
recorder: !include includes/recorder.yaml
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
telegram_bot: !include includes/telegram_bot.yaml
zone: !include includes/zone.yaml

#=====================
# Enabled components
#=====================

#introduction:
frontend:
config:
history:
logbook:
map:
sun:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Discover some devices automatically
# NOTE: the discovery component must be enabled for konnected
discovery:

# Text to speech
tts:
  - platform: google

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

#=====================
# Other components
#=====================

#arlo:
#  username: !secret arlo_username
#  password: !secret arlo_password
#
#camera:
#  - platform: arlo
#    ffmpeg_arguments: '-pred 1 -q:v 2'

climate:
  - platform: zwave

ffmpeg:

influxdb:
  host: 192.168.2.90

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key
