homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # https://www.gps-coordinates.net/:
  elevation: 133
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize
  #customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

#========================
# default_config enables:
#========================

#automation:		listed under 'Includes' below
#cloud:			listed under 'Includes' below
config:
#frontend:		listed under 'Includes' below
history:
logbook:
map:
mobile_app:
#person:		listed under 'Includes' below
#script:		listed under 'Includes' below
ssdp:
sun:
system_health:
updater:
zeroconf:

#=====================
# Includes
#=====================

alarm_control_panel: !include includes/alarm_control_panel.yaml
alexa_media: !include includes/alexa_media.yaml
automation: !include_dir_merge_list automation
#automation: !include automations.yaml
binary_sensor: !include_dir_merge_list binary_sensor
cloud: !include includes/cloud.yaml
device_tracker: !include includes/device_tracker.yaml
emulated_hue: !include includes/emulated_hue.yaml
frontend: !include includes/frontend.yaml
group: !include groups.yaml
input_boolean: !include includes/input_boolean.yaml
ios: !include includes/ios.yaml
konnected: !include includes/konnected.yaml
media_player: !include includes/media_player.yaml
logger: !include includes/logger.yaml
mqtt: !include includes/mqtt.yaml
notify: !include includes/notify.yaml
person: !include includes/person.yaml
python_script:
recorder: !include includes/recorder.yaml
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
speedtestdotnet: !include includes/speedtestdotnet.yaml
telegram_bot: !include includes/telegram_bot.yaml
vacuum: !include includes/vacuum.yaml
zone: !include includes/zone.yaml

#=====================
# Enabled components
#=====================

#introduction:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Discover some devices automatically
# NOTE: the discovery component must be enabled for konnected
discovery:

# Text to speech
tts:
  - platform: google_translate

#=====================
# Other components
#=====================

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

climate:
  - platform: zwave

ffmpeg:

influxdb:
  host: 192.168.2.55

pi_hole:
  - host: 192.168.2.50
    name: 'pihole1'
    ssl: false
    verify_ssl: false
    api_key: !secret pihole1_api_key
  - host: 192.168.2.51
    name: 'pihole2'
    ssl: false
    verify_ssl: false
    api_key: !secret pihole2_api_key

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key

#======================================
# HACS (Home Assistant Community Store)
#======================================

hacs:
  token: !secret hacs_access_token
  appdaemon: True
  options:
    country: US

breaking_changes:

