#default_view:
home2:
  name: Home2
  view: yes
  icon: mdi:home
  entities:
    - group.presence
    - group.all_deadbolts
    - group.doors_windows
    - group.binary_sensors
#    - group.front_locks
#    - sensor.tom_badge
    - alarm_control_panel.arlo_base
    - alarm_control_panel.home_alarm
#    - zone.home
#    - zone.office

climate:
  name: Climate
  view: yes
  icon: mdi:weather-partlycloudy
  entities:
    - weather.dark_sky
    - group.my_weather_darksky
    - sun.sun
    - sensor.yr_symbol
    - group.thermostat_controls
    - group.ct101_thermostat_downstairs
    - group.ct101_thermostat_upstairs

cameras:
  name: Cameras
  view: yes
  icon: mdi:camera
  entities:
    - camera.front_walk_camera
    - camera.front_door_camera
    - camera.back_door_camera
    - camera.back_porch_camera
    - camera.garage_camera
    - alarm_control_panel.arlo_base
    - sensor.arlo_cameras
    - group.camera_captured_today
    - group.camera_last_capture
    - group.camera_signal_strength

media_players:
  name: Media Players
  view: yes
  icon: mdi:music
  entities:
    - group.amazon_echos
    - media_player.this_device
    - media_player.txnr777_0009b0ebccdf

automation:
  name: Automation
  view: yes
  icon: mdi:home-automation
  entities:
    - group.all_automations
    - group.all_scripts

status:
  name: Status
  view: yes
  entities:
    - zwave.aeotec_zw090_zstick_gen5_us
    - zwave.aeotec_zw117_range_extender_6
    - zwave.front_deadbolt
    - zwave.kitchen_deadbolt
    - zwave.back_deadbolt
    - zwave.laundry_deadbolt
    - zwave.mbr_deadbolt
    - zwave.office_dimmer
    - zwave.zooz_zen06
    - zwave.washing_machine
    - zwave.freezer
    - zwave.ct101_thermostat_downstairs
    - zwave.ct101_thermostat_upstairs
    - group.monitor_sensors
    - group.presence_entities
    - group.input_boolean
    - group.pi_hole

testing:
  name: Testing
  view: yes
  entities:
    - group.amazon_fire7
    - group.amazon_unused_devices
    - group.zooz_zen06_switch
    - group.washing_machine
    - group.freezer
    - group.front_door

default_groups:
  name: Default Groups
  view: yes
  entities:
    - group.all_devices
    - group.all_lights
    - group.all_switches
    #- group.status
    - group.all_locks
    - group.all_remotes

presence:
  name: Presence
  entities:
    - group.tom_presence
    - group.mitzi_presence
    - group.brandon_presence
    - group.krystle_presence

tom_presence:
  name: Tom
  entities:
# nmap
#    - device_tracker.toms_iphone_nmap
# owntracks
#    - device_tracker.tom_iphone
# hass
    - device_tracker.iphone
# monitor
    - device_tracker.toms_iphone_monitor
# iphonedetect
    - device_tracker.toms_iphone_detect

mitzi_presence:
  name: Mitzi
  entities:
# nmap
#    - device_tracker.mitzis_iphone_nmap
# hass
    - device_tracker.nanas_iphone
# monitor
    - device_tracker.mitzis_iphone_monitor
# iphonedetect
    - device_tracker.mitzis_iphone_detect

brandon_presence:
  name: Brandon
  entities:
# nmap
#    - device_tracker.brandons_iphone_nmap
# monitor
    - device_tracker.brandons_iphone_monitor
# iphonedetect
    - device_tracker.brandons_iphone_detect

krystle_presence:
  name: Krystle
  entities:
# nmap
#    - device_tracker.krystles_iphone_nmap
# monitor
#    - device_tracker.krystles_iphone_monitor
# iphonedetect
    - device_tracker.krystles_iphone_detect

presence_entities:
  name: Presence Entities
  entities:
    - person.tom
    - device_tracker.tom
    - device_tracker.toms_iphone_nmap
    - device_tracker.tom_iphone
    - device_tracker.iphone
    - device_tracker.toms_iphone_monitor
    - device_tracker.toms_iphone_detect
    - person.mitzi
    - device_tracker.mitzi
    - device_tracker.mitzis_iphone_nmap
    - device_tracker.nanas_iphone
    - device_tracker.mitzis_iphone_monitor
    - device_tracker.mitzis_iphone_detect
    - person.brandon
    - device_tracker.brandon
    - device_tracker.brandons_iphone_nmap
    - device_tracker.brandons_iphone_monitor
    - device_tracker.brandons_iphone_detect
    - person.krystle
    - device_tracker.krystle
    - device_tracker.krystles_iphone_nmap
#    - device_tracker.krystles_iphone_monitor
    - device_tracker.krystles_iphone_detect
    - device_tracker.toms_ipad_nmap
    - device_tracker.toms_work_iphone_nmap
    - device_tracker.toms_work_ipad_nmap
    - input_boolean.tom_occupancy
    - input_boolean.mitzi_occupancy
    - input_boolean.brandon_occupancy
    - input_boolean.krystle_occupancy
    - input_boolean.arrival_scan_needed
    - input_boolean.departure_scan_needed
    - input_boolean.guest_mode

monitor_sensors:
  name: Monitor Sensors
  entities:
    - sensor.tom_media_closet
    - sensor.tom_home_occupancy_confidence
    - sensor.mitzi_media_closet
    - sensor.mitzi_home_occupancy_confidence
    - sensor.brandon_media_closet
    - sensor.brandon_home_occupancy_confidence
    - sensor.krystle_media_closet
    - sensor.krystle_home_occupancy_confidence

front_locks:
  name: Front Locks
  entities:
    - lock.front_deadbolt_locked
    - lock.kitchen_deadbolt_locked

back_locks:
  name: Back Locks
  entities:
    - lock.back_deadbolt_locked
    - lock.laundry_deadbolt_locked

all_deadbolts:
  name: All Deadbolts
  entities:
    - lock.front_deadbolt_locked
    - lock.kitchen_deadbolt_locked
    - lock.back_deadbolt_locked
    - lock.laundry_deadbolt_locked
    - lock.mbr_deadbolt_locked

binary_sensors:
  name: Binary Sensors
  entities:
    - binary_sensor.smoke_detectors

doors_windows:
  name: Doors & Windows
  entities:
    #    - binary_sensor.doors
    - binary_sensor.unknown_door
    - binary_sensor.front_kitchen_doors
    - binary_sensor.back_laundry_doors
    - binary_sensor.master_bedroom_doors
    - binary_sensor.garage_windows_storage_doors
    - binary_sensor.kitchen_dining_windows
    - binary_sensor.living_room_windows
    - binary_sensor.office_craft_bath_windows
    - binary_sensor.upstairs_windows

doors:
  name: Doors
  entities:
    - binary_sensor.unknown_door
    - binary_sensor.front_kitchen_doors
    - binary_sensor.back_laundry_doors
    - binary_sensor.master_bedroom_doors

windows:
  name: Windows
  entities:
    - binary_sensor.kitchen_dining_windows
    - binary_sensor.living_room_windows
    - binary_sensor.office_craft_bath_windows
    - binary_sensor.upstairs_windows

amazon_fire7:
  name: Touchscreens
  entities:
    - media_player.toms_2nd_fire
    - media_player.toms_3rd_fire
    - media_player.toms_4th_fire

amazon_unused_devices:
  name: Unused Amazon Devices
  entities:
    - media_player.mitzi_s_alexa_apps
    - media_player.tom_s_alexa_apps
    - media_player.tom_s_echo_dot
    - media_player.tom_s_fire_tv_stick
    - media_player.tom_s_2nd_fire
    - media_player.tom_s_3rd_fire
    - media_player.tom_s_4th_fire

amazon_echos:
  name: All Amazon Echos
  entities:
    - media_player.bedroom_alexa
    - media_player.craft_room_alexa
    - media_player.living_room_alexa
    - media_player.kitchen_alexa
    - media_player.office_alexa
#    - media_player.pool_alexa

amazon_echos_except_office:
  name: All Amazon Echos, except Office
  entities:
    - media_player.bedroom_alexa
    - media_player.craft_room_alexa
    - media_player.living_room_alexa
    - media_player.kitchen_alexa
#    - media_player.pool_alexa

my_weather_darksky:
  name: Weather from Dark Sky
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_daily_summary
##  - precip_type returns sensor.dark_sky_precip
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_intensity
##  - precip_intensity_max returns sensor.dark_sky_daily_max_precip_intensity
    - sensor.dark_sky_daily_max_precip_intensity
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_precip_accumulation
    - sensor.dark_sky_temperature
##  - temperature_high returns sensor.dark_sky_daytime_high_temperature
    - sensor.dark_sky_daytime_high_temperature
##  - temperature_low returns sensor.dark_sky_overnight_low_temperature
    - sensor.dark_sky_overnight_low_temperature
#    - sensor.dark_sky_dew_point
    - sensor.dark_sky_apparent_temperature
##  - apparent_temperature_high returns sensor.dark_sky_daytime_high_apparent_temperature
    - sensor.dark_sky_daytime_high_apparent_temperature
##  - apparent_temperature_low returns sensor.dark_sky_overnight_low_apparent_temperature
    - sensor.dark_sky_overnight_low_apparent_temperature
    - sensor.dark_sky_wind_bearing
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_wind_gust
##  - cloud_cover returns sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_humidity
#    - sensor.dark_sky_pressure
    - sensor.dark_sky_visibility
#    - sensor.dark_sky_ozone
#    - sensor.dark_sky_uv_index
#    - sensor.dark_sky_icon
    - sensor.dark_sky_nearest_storm_bearing
    - sensor.dark_sky_nearest_storm_distance
#    - sensor.dark_sky_moon_phase
    - sensor.dark_sky_sunrise_time
    - sensor.dark_sky_sunset_time

camera_captured_today:
  name: '# of videos captured today'
  entities:
    - sensor.captured_today_front_walk_camera
    - sensor.captured_today_front_door_camera
    - sensor.captured_today_back_door_camera
    - sensor.captured_today_back_porch_camera
    - sensor.captured_today_garage_camera

camera_last_capture:
  name: Date/time of last video
  entities:
    - sensor.last_front_walk_camera
    - sensor.last_front_door_camera
    - sensor.last_back_door_camera
    - sensor.last_back_porch_camera
    - sensor.last_garage_camera

camera_signal_strength:
  name: Wireless signal strength
  entities:
    - sensor.signal_strength_front_walk_camera
    - sensor.signal_strength_front_door_camera
    - sensor.signal_strength_back_door_camera
    - sensor.signal_strength_back_porch_camera
    - sensor.signal_strength_garage_camera

zooz_zen06_switch:
  name: Zooz ZEN06 Switch
  entities:
    - zwave.zooz_zen06
    - switch.zooz_zen06_switch
    - sensor.zooz_zen06_current
    - sensor.zooz_zen06_energy
    - sensor.zooz_zen06_power
    - sensor.zooz_zen06_previous_reading
    - sensor.zooz_zen06_voltage

washing_machine:
  name: Washing Machine
  entities:
    - zwave.washing_machine
    - switch.washing_machine_switch
    - sensor.washing_machine_current
    - sensor.washing_machine_energy
    - sensor.washing_machine_power
    - sensor.washing_machine_previous_reading
    - sensor.washing_machine_voltage

freezer:
  name: Freezer
  entities:
    - zwave.freezer
    - switch.freezer_switch
    - sensor.freezer_current
    - sensor.freezer_energy
    - sensor.freezer_power
    - sensor.freezer_previous_reading
    - sensor.freezer_voltage

thermostat_controls:
  name: Thermostat Controls
  entities:
    - input_boolean.thermostat_enable
    - input_boolean.thermostat_away_mode
    - input_boolean.thermostat_aux_heat
    - input_boolean.thermostat_manual_override

ct101_thermostat_downstairs:
  name: Thermostat (Downstairs)
  entities:
    - zwave.ct101_thermostat_downstairs
    - sensor.ct101_thermostat_downstairs_temperature
    - sensor.ct101_thermostat_downstairs_humidity
    - climate.ct101_thermostat_downstairs_cooling_1
    - climate.ct101_thermostat_downstairs_heating_1
    - sensor.ct101_thermostat_downstairs_battery
    - sensor.ct101_thermostat_downstairs_cool_setting
    - sensor.ct101_thermostat_downstairs_heat_setting
    - sensor.ct101_thermostat_downstairs_indicator

ct101_thermostat_upstairs:
  name: Thermostat (Upstairs)
  entities:
    - zwave.ct101_thermostat_upstairs
    - sensor.ct101_thermostat_upstairs_temperature
    - sensor.ct101_thermostat_upstairs_humidity
    - climate.ct101_thermostat_upstairs_cooling_1
    - climate.ct101_thermostat_upstairs_heating_1
    - sensor.ct101_thermostat_upstairs_battery
    - sensor.ct101_thermostat_upstairs_cool_setting
    - sensor.ct101_thermostat_upstairs_heat_setting
    - sensor.ct101_thermostat_upstairs_indicator

input_boolean:
  name: Input Booleans
  entities:
    - input_boolean.tom_occupancy
    - input_boolean.mitzi_occupancy
    - input_boolean.brandon_occupancy
    - input_boolean.krystle_occupancy
    - input_boolean.arrival_scan_needed
    - input_boolean.departure_scan_needed
    - input_boolean.lock_all_doors
    - input_boolean.set_the_alarm
    - input_boolean.trash_day
    - input_boolean.alexa_enable

front_door:
  name: Front Deadbolt
  entities:
  - zwave.front_deadbolt
  - lock.front_deadbolt_locked
  - sensor.front_deadbolt_alarm_type
  - sensor.front_deadbolt_alarm_level
  - sensor.front_deadbolt_sourcenodeid
  - sensor.front_deadbolt_access_control
  - sensor.front_deadbolt_burglar
  - sensor.front_deadbolt_power_management
  - sensor.front_deadbolt_system
  - sensor.frontdoorbattery
  - sensor.front_door_code
  - sensor.front_last_action

pi_hole:
  name: Pi-hole statistics
  entities:
    - sensor.pihole_ads_blocked_today
    - sensor.pihole_ads_percentage_blocked_today
    - sensor.pihole_dns_queries_cached
    - sensor.pihole_dns_queries_forwarded
    - sensor.pihole_dns_queries_today
    - sensor.pihole_dns_unique_clients
    - sensor.pihole_dns_unique_domains
    - sensor.pihole_domains_blocked
    - sensor.pihole_seen_clients
