- platform: yr

- platform: darksky
  api_key: !secret darksky_api_key
  update_interval:
    minutes: 3
  monitored_conditions:
    - summary
    - minutely_summary
    - hourly_summary
    - daily_summary
##  - precip_type returns sensor.dark_sky_precip
    - precip_type
    - precip_intensity
##  - precip_intensity_max returns sensor.dark_sky_daily_max_precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_accumulation
    - temperature
##  - temperature_high returns sensor.dark_sky_daytime_high_temperature
    - temperature_high
##  - temperature_low returns sensor.dark_sky_overnight_low_temperature
    - temperature_low
#   - dew_point
    - apparent_temperature
##  - apparent_temperature_high returns sensor.dark_sky_daytime_high_apparent_temperature
#   - apparent_temperature_high
##  - apparent_temperature_low returns sensor.dark_sky_overnight_low_apparent_temperature
#   - apparent_temperature_low
    - wind_bearing
    - wind_speed
##  - cloud_cover returns sensor.dark_sky_cloud_coverage
    - cloud_cover
    - humidity
#   - pressure
    - visibility
#   - ozone
#   - uv_index
#   - icon
    - nearest_storm_bearing
    - nearest_storm_distance

- platform: mqtt
  state_topic: !secret tom_pizw-0_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Tom Media Closet'

- platform: mqtt
  state_topic: !secret mitzi_pizw-0_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Mitzi Media Closet'

- platform: mqtt
  state_topic: !secret brandon_pizw-0_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Brandon Media Closet'

- platform: mqtt
  state_topic: !secret krystle_pizw-0_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Krystle Media Closet'

#- platform: mqtt
#  state_topic: 'location/second floor/00:00:00:00:00:00'
#  value_template: '{{ value_json.confidence }}'
#  unit_of_measurement: '%'
#  name: 'Andrew Second Floor'
#
#- platform: mqtt
#  state_topic: 'location/third floor/00:00:00:00:00:00'
#  value_template: '{{ value_json.confidence }}'
#  unit_of_measurement: '%'
#  name: 'Andrew Third Floor'
#
#- platform: mqtt
#  state_topic: 'location/garage/00:00:00:00:00:00'
#  value_template: '{{ value_json.confidence }}'
#  unit_of_measurement: '%'
#  name: 'Andrew Garage'

- platform: min_max
  name: "Tom Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.tom_media_closet
#    - sensor.andrew_garage
#    - sensor.andrew_third_floor
#    - sensor.andrew_second_floor
#    - sensor.andrew_first_floor

- platform: min_max
  name: "Mitzi Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.mitzi_media_closet

- platform: min_max
  name: "Brandon Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.brandon_media_closet

- platform: min_max
  name: "Krystle Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.krystle_media_closet

- platform: template
  sensors:
    back_deadbolt_batteries:
      friendly_name: Back Deadbolt Batteries
      value_template: "{% if states.zwave.back_deadbolt %}
          {{ states.zwave.back_deadbolt.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.back_deadbolt_batteries')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}

- platform: template
  sensors:
    front_deadbolt_batteries:
      friendly_name: Front Deadbolt Batteries
      value_template: "{% if states.zwave.front_deadbolt %}
          {{ states.zwave.front_deadbolt.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.front_deadbolt_batteries')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}

- platform: template
  sensors:
    kitchen_deadbolt_batteries:
      friendly_name: Kitchen Deadbolt Batteries
      value_template: "{% if states.zwave.kitchen_deadbolt %}
          {{ states.zwave.kitchen_deadbolt.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.kitchen_deadbolt_batteries')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}

- platform: template
  sensors:
    laundry_deadbolt_batteries:
      friendly_name: Laundry Deadbolt Batteries
      value_template: "{% if states.zwave.laundry_deadbolt %}
          {{ states.zwave.laundry_deadbolt.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.laundry_deadbolt_batteries')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}

- platform: template
  sensors:
    mbr_deadbolt_batteries:
      friendly_name: MBR Deadbolt Batteries
      value_template: "{% if states.zwave.mbr_deadbolt %}
          {{ states.zwave.mbr_deadbolt.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.mbr_deadbolt_batteries')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}

- platform: template
  sensors:
    tom_badge:
      unit_of_measurement: Tom
      entity_id: group.tom_presence
      friendly_name_template: >
        {% if is_state('group.tom_presence', 'home') %}
          Home
        {% else %}
          Away
        {% endif %}
      value_template: >
        {% if is_state('group.tom_presence', 'home') %}
          Home
        {% else %}
          Away
        {% endif %}
      entity_picture_template: !secret tom_pic
