- platform: yr

- platform: darksky
  api_key: !secret darksky_api_key
  update_interval:
    minutes: 3
  monitored_conditions:
    - summary
    - minutely_summary
    - hourly_summary
    - daily_summary
##  - precip_type returns sensor.dark_sky_precip
    - precip_type
    - precip_intensity
##  - precip_intensity_max returns sensor.dark_sky_daily_max_precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_accumulation
    - temperature
##  - temperature_high returns sensor.dark_sky_daytime_high_temperature
    - temperature_high
##  - temperature_low returns sensor.dark_sky_overnight_low_temperature
    - temperature_low
#   - dew_point
    - apparent_temperature
##  - apparent_temperature_high returns sensor.dark_sky_daytime_high_apparent_temperature
#   - apparent_temperature_high
##  - apparent_temperature_low returns sensor.dark_sky_overnight_low_apparent_temperature
#   - apparent_temperature_low
    - wind_bearing
    - wind_speed
##  - cloud_cover returns sensor.dark_sky_cloud_coverage
    - cloud_cover
    - humidity
#   - pressure
    - visibility
#   - ozone
#   - uv_index
#   - icon
    - nearest_storm_bearing
    - nearest_storm_distance

- platform: mqtt
  state_topic: !secret tom_pizw-0_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Tom Media Closet'

- platform: mqtt
  state_topic: !secret mitzi_pizw-0_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Mitzi Media Closet'

- platform: mqtt
  state_topic: !secret brandon_pizw-0_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Brandon Media Closet'

- platform: mqtt
  state_topic: !secret krystle_pizw-0_topic
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Krystle Media Closet'

#- platform: mqtt
#  state_topic: 'location/second floor/00:00:00:00:00:00'
#  value_template: '{{ value_json.confidence }}'
#  unit_of_measurement: '%'
#  name: 'Andrew Second Floor'
#
#- platform: mqtt
#  state_topic: 'location/third floor/00:00:00:00:00:00'
#  value_template: '{{ value_json.confidence }}'
#  unit_of_measurement: '%'
#  name: 'Andrew Third Floor'
#
#- platform: mqtt
#  state_topic: 'location/garage/00:00:00:00:00:00'
#  value_template: '{{ value_json.confidence }}'
#  unit_of_measurement: '%'
#  name: 'Andrew Garage'

- platform: min_max
  name: "Tom Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.tom_media_closet
#    - sensor.andrew_garage
#    - sensor.andrew_third_floor
#    - sensor.andrew_second_floor
#    - sensor.andrew_first_floor

- platform: min_max
  name: "Mitzi Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.mitzi_media_closet

- platform: min_max
  name: "Brandon Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.brandon_media_closet

- platform: min_max
  name: "Krystle Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.krystle_media_closet

- platform: template
  sensors:
    tom_badge:
      unit_of_measurement: Tom
      entity_id: group.tom_presence
      friendly_name_template: >
        {% if is_state('group.tom_presence', 'home') %}
          Home
        {% else %}
          Away
        {% endif %}
      value_template: >
        {% if is_state('group.tom_presence', 'home') %}
          Home
        {% else %}
          Away
        {% endif %}
      entity_picture_template: !secret tom_pic
