title: Home
views:
  - title: Home
    icon: mdi:home
    cards:

      - type: entity-filter
        entities:
          - entity: device_tracker.toms_iphone_mqtt
            name: Tom
          - entity: device_tracker.mitzis_iphone_mqtt
            name: Mitzi
          - entity: device_tracker.brandons_iphone_mqtt
            name: Brandon
          - entity: device_tracker.krystles_iphone_mqtt
            name: Krystle
        state_filter:
          - 'home'
        card:
          type: glance
          title: Who is Home?
          show_state: false
          column_width: 25%

      - type: entities
        entities:
          - alarm_control_panel.home_alarm

      - type: entities
        title: All Deadbolts
        show_header_toggle: true
        entities:
          - lock.front_deadbolt_locked
          - lock.kitchen_deadbolt_locked
          - lock.back_deadbolt_locked
          - lock.laundry_deadbolt_locked
          - lock.mbr_deadbolt_locked

      - type: entities
        title: Doors & Windows
        show_header_toggle: true
        entities:
          - binary_sensor.unknown_door
          - binary_sensor.frontkitchen_doors
          - binary_sensor.backlaundry_doors
          - binary_sensor.master_bedroom_doors
          - binary_sensor.garage_windows_storage_doors
          - binary_sensor.kitchendining_windows
          - binary_sensor.living_room_windows
          - binary_sensor.officecraftbath_windows
          - binary_sensor.upstairs_windows

      - type: entities
        title: Binary Sensors
        show_header_toggle: true
        entities:
          - binary_sensor.smoke_detectors

  - title: Climate
    icon: mdi:weather-partlycloudy
    cards:
      - type: history-graph
        hours_to_show: 168
        refresh_interval: 3600
        entities:
          - sensor.dark_sky_temperature
          - sensor.ct101_thermostat_downstairs_temperature
          - sensor.ct101_thermostat_upstairs_temperature

      - type: entities
        entities:
          - sun.sun
          - sensor.yr_symbol

      - type: weather-forecast
        entity: weather.dark_sky

      - type: entities
        title: Thermostat Controls
        show_header_toggle: true
        entities:
          - input_boolean.thermostat_enable
          - input_boolean.thermostat_away_mode
          - input_boolean.thermostat_aux_heat
          - input_boolean.thermostat_manual_override

      - type: entities
        title: Thermostat (Downstairs)
        show_header_toggle: true
        entities:
          - sensor.ct101_thermostat_downstairs_temperature
          - climate.ct101_thermostat_downstairs_cooling_1
          - climate.ct101_thermostat_downstairs_heating_1
          - sensor.ct101_thermostat_downstairs_cool_setting
          - sensor.ct101_thermostat_downstairs_heat_setting

      - type: entities
        title: Thermostat (Upstairs)
        show_header_toggle: true
        entities:
          - sensor.ct101_thermostat_upstairs_temperature
          - climate.ct101_thermostat_upstairs_cooling_1
          - climate.ct101_thermostat_upstairs_heating_1
          - sensor.ct101_thermostat_upstairs_cool_setting
          - sensor.ct101_thermostat_upstairs_heat_setting

  - title: Media Players
    icon: mdi:music
    cards:
      - type: media-control
        entity: media_player.pool_house_echo_dot
      - type: media-control
        entity: media_player.toms_echo
      - type: media-control
        entity: media_player.toms_echo_show
      - type: media-control
        entity: media_player.this_device
      - type: media-control
        entity: media_player.txnr777_0009b0ebccdf

  - title: Automation
    icon: mdi:home-automation
    cards:
      - type: entities
        title: all automations
        show_header_toggle: true
        entities:
          - automation.alarm_state_change_alert
          - automation.alexa_lock_all_doors
          - automation.alexa_set_the_alarm
          - automation.back_door_is_unlocked
          - automation.beep_on_doorwindow_openclose
          - automation.brandon_is_away
          - automation.brandon_is_home
          - automation.close_the_door_10
          - automation.close_the_door_2
          - automation.close_the_door_20
          - automation.close_the_window_2
          - automation.device_state_change_alert
          - automation.disarm_alarm_when_door_unlocked_by_keypad
          - automation.freezer_failure
          - automation.front_door_is_unlocked
          - automation.group_is_away
          - automation.kitchen_door_is_unlocked
          - automation.krystle_is_away
          - automation.krystle_is_home
          - automation.laundry_door_is_unlocked
          - automation.lock_front_doors_at_sunset
          - automation.master_bedroom_door_is_unlocked
          - automation.mitzi_is_away
          - automation.mitzi_is_home
          - automation.notify_ios_that_back_door_is_unlocked
          - automation.notify_ios_that_front_door_is_unlocked
          - automation.notify_ios_that_kitchen_door_is_unlocked
          - automation.notify_ios_that_laundry_room_door_is_unlocked
          - automation.notify_ios_that_master_bedroom_door_is_unlocked
          - automation.recycle_pickup_day_changed
          - automation.recycle_pickup_week_changed
          - automation.remind_later
          - automation.reset_hvac_master_switch
          - automation.reset_trash_reminders
          - automation.restore_trash_recycle_settings_on_startup
          - automation.telegram_callback_to_display_menu
          - automation.telegram_callback_to_remove_keyboard
          - automation.telegram_callback_to_repeat_message_in_1_hour
          - automation.telegram_callback_to_repeat_message_in_30_minutes
          - automation.thermostat_change_on_weather
          - automation.tom_has_arrived_at_work
          - automation.tom_has_departed_work
          - automation.tom_is_away
          - automation.tom_is_home
          - automation.trash_pickup_day_changed
          - automation.trash_and_recycle_bin_left_outside_already
          - automation.trash_and_recycle_pickup_reminder
          - automation.trigger_alarm_while_armed_away
          - automation.trigger_alarm_while_armed_home
          - automation.trigger_monitorsh_arrival_scan_on_door_open
          - automation.trigger_monitorsh_departure_scan_on_door_close
          - automation.verify_doorswindows_are_closed
          - automation.washing_machine_is_off
          - automation.washing_machine_is_on
          - automation.battery_notification
          - automation.battery_notification_clear
          - automation.battery_notification_pushover
          - automation.battery_notification_slack
          - automation.battery_notification_telegram
          - automation.battery_sensor_from_attributes
          - automation.clear_mqtt_topic
          - automation.ios_push_action_to_lock_back_door
          - automation.ios_push_action_to_lock_front_door
          - automation.ios_push_action_to_lock_kitchen_door
          - automation.ios_push_action_to_lock_laundry_room_door
          - automation.ios_push_action_to_lock_master_bedroom_door
          - automation.notify_via_telegram_on_home_assistant_start
          - automation.notify_via_telegram_to_put_trash_bin_out
          - automation.perform_departure_scan
          - automation.report_manual_temp_adjustment
          - automation.update_battery_status_group_members
          - automation.zwave_device_dead

      - type: entities
        title: all scripts
        show_header_toggle: true
        entities:
          - script.test_push
          - script.test_telegram
          - script.thermostat_away_mode
          - script.thermostat_home_mode

  - title: Status
    cards:
      - type: entities
        entities:
          - zwave.aeotec_zw090_zstick_gen5_us
          - zwave.aeotec_zw117_range_extender_6
          - zwave.front_deadbolt
          - zwave.kitchen_deadbolt
          - zwave.back_deadbolt
          - zwave.laundry_deadbolt
          - zwave.mbr_deadbolt
          - zwave.office_dimmer
          - zwave.zooz_zen06
          - zwave.washing_machine
          - zwave.freezer
          - zwave.ct101_thermostat_downstairs
          - zwave.ct101_thermostat_upstairs

      - type: entities
        title: Monitor Sensors
        show_header_toggle: true
        entities:
          - sensor.tom_media_closet
          - sensor.tom_home_occupancy_confidence
          - sensor.mitzi_media_closet
          - sensor.mitzi_home_occupancy_confidence
          - sensor.brandon_media_closet
          - sensor.brandon_home_occupancy_confidence
          - sensor.krystle_media_closet
          - sensor.krystle_home_occupancy_confidence

      - type: entities
        title: Presence Entities
        show_header_toggle: true
        entities:
          - device_tracker.toms_iphone_nmap
          - device_tracker.toms_iphone_mqtt
          - device_tracker.toms_iphone
          - device_tracker.tom_iphone
          - device_tracker.mitzis_iphone_nmap
          - device_tracker.mitzis_iphone_mqtt
          - device_tracker.mitzis_iphone
          - device_tracker.brandons_iphone_nmap
          - device_tracker.brandons_iphone_mqtt
          - device_tracker.krystles_iphone_nmap
          - device_tracker.krystles_iphone_mqtt
          - input_boolean.tom_occupancy
          - input_boolean.mitzi_occupancy
          - input_boolean.brandon_occupancy
          - input_boolean.krystle_occupancy
          - input_boolean.departure_scan_needed

      - type: entities
        title: Input Booleans
        show_header_toggle: true
        entities:
          - input_boolean.tom_occupancy
          - input_boolean.mitzi_occupancy
          - input_boolean.brandon_occupancy
          - input_boolean.krystle_occupancy
          - input_boolean.departure_scan_needed
          - input_boolean.lock_all_doors
          - input_boolean.set_the_alarm

  - title: Testing
    cards:
      - type: media-control
        entity: media_player.toms_2nd_fire
      - type: media-control
        entity: media_player.toms_3rd_fire
      - type: media-control
        entity: media_player.toms_4th_fire
      - type: media-control
        entity: media_player.mitzis_alexa_apps
      - type: media-control
        entity: media_player.toms_alexa_apps
      - type: media-control
        entity: media_player.toms_echo_dot
      - type: media-control
        entity: media_player.toms_fire_tv_stick
      - type: entities
        title: Zooz ZEN06 Switch
        show_header_toggle: true
        entities:
          - zwave.zooz_zen06
          - switch.zooz_zen06_switch
          - sensor.zooz_zen06_current
          - sensor.zooz_zen06_energy
          - sensor.zooz_zen06_power
          - sensor.zooz_zen06_previous_reading
          - sensor.zooz_zen06_voltage

      - type: entities
        title: Washing Machine
        show_header_toggle: true
        entities:
          - zwave.washing_machine
          - switch.washing_machine_switch
          - sensor.washing_machine_current
          - sensor.washing_machine_energy
          - sensor.washing_machine_power
          - sensor.washing_machine_previous_reading
          - sensor.washing_machine_voltage

      - type: entities
        title: Freezer
        show_header_toggle: true
        entities:
          - zwave.freezer
          - switch.freezer_switch
          - sensor.freezer_current
          - sensor.freezer_energy
          - sensor.freezer_power
          - sensor.freezer_previous_reading
          - sensor.freezer_voltage

      - type: entities
        title: Front Deadbolt
        show_header_toggle: true
        entities:
          - zwave.front_deadbolt
          - lock.front_deadbolt_locked
          - sensor.front_deadbolt_alarm_type
          - sensor.front_deadbolt_alarm_level
          - sensor.front_deadbolt_sourcenodeid
          - sensor.front_deadbolt_access_control
          - sensor.front_deadbolt_burglar
          - sensor.front_deadbolt_power_management
          - sensor.front_deadbolt_system
          - sensor.front_door_code
          - sensor.front_last_action

  - title: Default Groups
    cards:
      - type: entities
        title: all devices
        show_header_toggle: true
        entities:
          - device_tracker.toms_iphone_nmap
          - device_tracker.mitzis_iphone_nmap
          - device_tracker.brandons_iphone_nmap
          - device_tracker.krystles_iphone_nmap
          - device_tracker.toms_iphone
          - device_tracker.mitzis_iphone
          - device_tracker.tom_iphone
          - device_tracker.toms_iphone_mqtt
          - device_tracker.mitzis_iphone_mqtt
          - device_tracker.brandons_iphone_mqtt
          - device_tracker.krystles_iphone_mqtt

      - type: entities
        title: all lights
        show_header_toggle: true
        entities:
          - light.office_dimmer_level

      - type: entities
        title: all switches
        show_header_toggle: true
        entities:
          - switch.beep_beep
          - switch.siren
          - switch.warning
          - switch.zooz_zen06_switch
          - switch.washing_machine_switch
          - switch.freezer_switch

      - type: entities
        title: all locks
        show_header_toggle: true
        entities:
          - lock.back_deadbolt_locked
          - lock.front_deadbolt_locked
          - lock.kitchen_deadbolt_locked
          - lock.laundry_deadbolt_locked
          - lock.mbr_deadbolt_locked

      - type: entities
        title: all remotes
        show_header_toggle: true
        entities:
          - remote.living_room

  - title: Batteries
    icon: mdi:battery-alert
    cards:
      - type: entities
        title: Battery Status
        show_header_toggle: false
        entities:
          - sensor.back_deadbolt_battery
          - sensor.ct101_thermostat_downstairs_battery
          - sensor.ct101_thermostat_upstairs_battery
          - sensor.front_deadbolt_battery
          - sensor.kitchen_deadbolt_battery
          - sensor.laundry_deadbolt_battery
          - sensor.mbr_deadbolt_battery
          - sensor.nanas_iphone_battery_level
          - sensor.toms_iphone_battery_level

      - type: entities
        title: Battery Alert
        show_header_toggle: false
        entities:
          - input_number.battery_alert_threshold_min
          - input_number.battery_alert_threshold_max
          - input_text.clear_mqtt_topic
          - automation.battery_notification
          - automation.battery_notification_clear
          - automation.battery_notification_slack
          - automation.battery_notification_telegram
          - automation.battery_notification_pushover
          - automation.battery_sensor_from_attributes
          - automation.update_battery_status_group_members
          - automation.clear_mqtt_topic
