- platform: template
  sensors:
    # this sensor is intended to capture the user number that was used during
    # the last operation that required a code to be entered.  it will persist
    # after subsequent other events (manual locking, etc.) that didn't involve
    # a user code
    front_door_code:
      friendly_name: Front Door Last Code
      entity_id:
        - sensor.front_deadbolt_alarm_type
        - sensor.front_deadbolt_alarm_level
      value_template: >-
        {% if is_state('sensor.front_deadbolt_alarm_type', '18') or
              is_state('sensor.front_deadbolt_alarm_type', '19') %}
          {% if not is_state('sensor.front_deadbolt_alarm_level', '0') %}
            {{states('sensor.front_deadbolt_alarm_level')}}
          {% else %}
            {# just provide previous value if no user code entered #}
            {{states('sensor.front_door_code')}}
          {% endif %}
        {% else %}
          {# just provide previous value if no user code entered #}
          {{states('sensor.front_door_code')}}
        {% endif %}
    front_last_action:
      friendly_name: 'Front Door Last Action'
      entity_id:
        - sensor.front_deadbolt_alarm_type
        - sensor.front_deadbolt_alarm_level
      value_template: >-
        {% if is_state('sensor.front_deadbolt_alarm_type', '18') %}
          {% if is_state('sensor.front_deadbolt_alarm_level', '0') %}
        Locked: Outside Keypad
          {% else %}
        Locked: User {{states('sensor.front_deadbolt_alarm_level')}}
          {% endif %}
        {% elif is_state('sensor.front_deadbolt_alarm_type', '19') %}
          Unlocked: User Code {{states('sensor.front_deadbolt_alarm_level')}}
        {% elif is_state('sensor.front_deadbolt_alarm_type', '21') %}
          Locked: {{[ 'Outside Lock', 'Inside Deadbolt', 'Outside Keypad' ][states('sensor.front_deadbolt_alarm_level')|int]}}
        {% elif is_state('sensor.front_deadbolt_alarm_type', '22') %}
          Unlocked: Inside Deadbolt
        {% else %}
          Unknown: {{states('sensor.front_deadbolt_alarm_type')}}/{{states('sensor.front_deadbolt_alarm_level')}}
        {% endif %}
