- alias: Freezer failure
  initial_state: true
  hide_entity: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.freezer_power
    above: 100
    for:
      minutes: 180
  - platform: numeric_state
    entity_id: sensor.freezer_power
    below: 100
    for:
      minutes: 60
  action:
    - service: notify.telegram_tom
      data:
        message: "The freezer has failed."
