- platform: darksky
  api_key: !secret darksky_api_key
  scan_interval:
    minutes: 3
#  forecast:
#    - 0
#    - 1
#    - 2
#    - 3
#    - 4
#    - 5
#    - 6
#    - 7
  monitored_conditions:
    - summary
    - minutely_summary
    - hourly_summary
    - daily_summary
##  - precip_type returns sensor.dark_sky_precip
    - precip_type
    - precip_intensity
##  - precip_intensity_max returns sensor.dark_sky_daily_max_precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_accumulation
    - temperature
##  - temperature_high returns sensor.dark_sky_daytime_high_temperature
    - temperature_high
##  - temperature_low returns sensor.dark_sky_overnight_low_temperature
    - temperature_low
#   - dew_point
    - apparent_temperature
##  - apparent_temperature_high returns sensor.dark_sky_daytime_high_apparent_temperature
#   - apparent_temperature_high
##  - apparent_temperature_low returns sensor.dark_sky_overnight_low_apparent_temperature
#   - apparent_temperature_low
    - wind_bearing
    - wind_speed
    - wind_gust
##  - cloud_cover returns sensor.dark_sky_cloud_coverage
    - cloud_cover
    - humidity
#   - pressure
    - visibility
#   - ozone
#   - uv_index
#   - icon
    - nearest_storm_bearing
    - nearest_storm_distance
#    - moon_phase
    - sunrise_time
    - sunset_time
