- platform: template
  sensors:
    pihole_ads_blocked_today:
      friendly_name: 'Ads Blocked Today'
      value_template: "{{ states('sensor.pihole1_ads_blocked_today')|int + states('sensor.pihole2_ads_blocked_today')|int }}"
    pihole_ads_percentage_blocked_today:
      friendly_name: 'Percentage of Ads Blocked Today'
      value_template: "{{ ( (states('sensor.pihole1_ads_blocked_today')|int + states('sensor.pihole2_ads_blocked_today')|int) / (states('sensor.pihole1_dns_queries_today')|int + states('sensor.pihole2_dns_queries_today')|int) * 100 )|round(2)|string + ' %' }}"
    pihole_dns_queries_today:
      friendly_name: 'DNS Queries Today'
      value_template: "{{ states('sensor.pihole1_dns_queries_today')|int + states('sensor.pihole2_dns_queries_today')|int }}"
    pihole_domains_blocked:
      friendly_name: 'DNS Domains Blocked'
      value_template: "{{ [states('sensor.pihole1_domains_blocked'), states('sensor.pihole2_domains_blocked')]|max }}"
#    pihole_dns_queries_cached:
#      friendly_name: 'DNS Queries Cached'
#      value_template: "{{ states('sensor.pihole1_dns_queries_cached')|int + states('sensor.pihole2_dns_queries_cached')|int }}"
#    pihole_dns_queries_forwarded:
#      friendly_name: 'DNS Queries Forwarded'
#      value_template: "{{ states('sensor.pihole1_dns_queries_forwarded')|int + states('sensor.pihole2_dns_queries_forwarded')|int }}"
#    pihole_dns_unique_domains:
#      friendly_name: 'DNS Unique Domains'
#      value_template: "{{ states('sensor.pihole1_dns_unique_domains')|int + states('sensor.pihole2_dns_unique_domains')|int }}"
