- alias: Alarm State Change Alert
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: alarm_control_panel.home_alarm
  action:
  - service: notify.alexa_media
    data_template:
      target: media_player.office_alexa
      data:
        type: announce
        method: all
      message: ' 
        {% if trigger.to_state.state == ''triggered'' %}ALERT! The alarm has been triggered!
        {% else %}
          {{ trigger.to_state.attributes.friendly_name }} is 
          {% if trigger.to_state.state == ''armed_away'' %}in away mode
          {% elif trigger.to_state.state == ''armed_home'' %}in home mode
          {% elif trigger.to_state.state == ''armed_night'' %}in night mode
          {% elif trigger.to_state.state == ''pending'' %}pending mode change
          {% else %}disarmed{% endif %}.
        {% endif %} '
  - service: notify.mobile_app_iphone
    data_template:
      title: 'ALARM'
      message: ' 
        {% if trigger.to_state.state == ''triggered'' %}ALERT! The alarm has been triggered!
        {% else %}
          {{ trigger.to_state.attributes.friendly_name }} is 
          {% if trigger.to_state.state == ''armed_away'' %}in away mode
          {% elif trigger.to_state.state == ''armed_home'' %}in home mode
          {% elif trigger.to_state.state == ''armed_night'' %}in night mode
          {% elif trigger.to_state.state == ''pending'' %}pending mode change
          {% else %}disarmed{% endif %}.
        {% endif %} '
  - service: notify.telegram_tom
    data_template:
      message: ' 
        {% if trigger.to_state.state == ''triggered'' %}ALERT! The alarm has been triggered!
        {% else %}
          {{ trigger.to_state.attributes.friendly_name }} is 
          {% if trigger.to_state.state == ''armed_away'' %}in away mode
          {% elif trigger.to_state.state == ''armed_home'' %}in home mode
          {% elif trigger.to_state.state == ''armed_night'' %}in night mode
          {% elif trigger.to_state.state == ''pending'' %}pending mode change
          {% else %}disarmed{% endif %}.
        {% endif %} '

- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: group.doors_windows
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm

- alias: 'Trigger alarm while armed home'
  trigger:
    - platform: state
      entity_id: group.doors_windows
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm

#- alias: 'Arm alarm when door locked by keypad'
#  trigger:
#    - platform: state
#      entity_id: 
#        - sensor.front_deadbolt_alarm_type
#        - sensor.kitchen_deadbolt_alarm_type
#        - sensor.back_deadbolt_alarm_type
#        - sensor.laundry_deadbolt_alarm_type
#        - sensor.mbr_deadbolt_alarm_type
#      to: '18'
#  action:
#    - service: alarm_control_panel.alarm_arm_home
#      entity_id: alarm_control_panel.home_alarm
#      data:
#        code: !secret alarm_code

- alias: 'Disarm alarm when door unlocked by keypad'
  trigger:
    - platform: state
      entity_id: 
        - sensor.front_deadbolt_alarm_type
        - sensor.kitchen_deadbolt_alarm_type
        - sensor.back_deadbolt_alarm_type
        - sensor.laundry_deadbolt_alarm_type
        - sensor.mbr_deadbolt_alarm_type
      to: '19'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
      data:
        code: !secret alarm_code
