- alias: Lock Front Doors At Sunset
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
  action:
    service: lock.lock
    entity_id: group.front_locks

- alias: Group is away
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.presence
    to: not_home
  action:
    - service: lock.lock
      entity_id: group.all_locks
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
      data:
        code: !secret alarm_code
    - service: notify.telegram_tom
      data:
        message: The house is now empty, so I locked all doors.

- alias: Beep on Door/Window Open/Close
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
#    - binary_sensor.garage_windows_storage_doors
    - binary_sensor.kitchendining_windows
    - binary_sensor.living_room_windows
    - binary_sensor.officecraftbath_windows
#    - binary_sensor.upstairs_windows
  action:
  - service: switch.turn_on
    entity_id: switch.beep_beep

- alias: Trigger monitor.sh arrival scan on Door Open
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'off'
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: monitor/scan/arrive

- alias: Trigger monitor.sh departure scan on Door Close
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'on'
    to: 'off'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.departure_scan_needed

- alias: Close The Door (2)
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'off'
    to: 'on'
    for:
      minutes: 2
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Please close the door!
  - service: notify.telegram_tom
    data:
      message: Door is open (2)

- alias: Close The Door (10)
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'off'
    to: 'on'
    for:
      minutes: 10
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: A door has been open for ten minutes. Please close the door!
  - service: notify.telegram_tom
    data:
      message: Door is open (10)

- alias: Close The Door (20)
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.unknown_door
    - binary_sensor.frontkitchen_doors
    - binary_sensor.backlaundry_doors
    - binary_sensor.master_bedroom_doors
    from: 'off'
    to: 'on'
    for:
      minutes: 20
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Please check all doors. A door has been open for over twenty minutes, so I am turning off the thermostat.
  - service: notify.living_room_tv
    data:
      message: Please check all doors. A door has been open for over twenty minutes, so I am turning off the thermostat.
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.thermostat_enable
  - service: notify.telegram_tom
    data:
      message: Door is open (20)

- alias: Close The Window (2)
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
    - binary_sensor.kitchendining_windows
    - binary_sensor.living_room_windows
    - binary_sensor.officecraftbath_windows
    - binary_sensor.upstairs_windows
    from: 'off'
    to: 'on'
    for:
      minutes: 2
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Please check all windows. A window is open, so I am turning off the thermostat.
  - service: notify.living_room_tv
    data:
      message: Please check all windows. A window is open, so I am turning off the thermostat.
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.thermostat_enable
  - service: notify.telegram_tom
    data:
      message: Window is open (2)

- alias: Reset HVAC master switch
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.doors_windows
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: input_boolean.thermostat_enable
    state: 'off'
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: All doors and windows have been closed, so I am reseting the thermostat.
  - service: notify.living_room_tv
    data:
      message: All doors and windows have been closed, so I am reseting the thermostat.
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.thermostat_enable
  - service: notify.telegram_tom
    data:
      message: HVAC master switch has been reset

- alias: Front door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '22:05:00'
  condition:
  - condition: state
    entity_id: lock.front_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the front door is still unlocked!
  - service: notify.living_room_tv
    data:
      message: Warning, the front door is still unlocked!

- alias: Kitchen door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '22:06:00'
  condition:
  - condition: state
    entity_id: lock.kitchen_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the kitchen door is still unlocked!
  - service: notify.living_room_tv
    data:
      message: Warning, the kitchen door is still unlocked!

- alias: Master bedroom door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '22:07:00'
  condition:
  - condition: state
    entity_id: lock.mbr_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the master bedroom door is still unlocked!
  - service: notify.living_room_tv
    data:
      message: Warning, the master bedroom door is still unlocked!

- alias: Back door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: lock.back_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the back door is still unlocked!
  - service: notify.living_room_tv
    data:
      message: Warning, the back door is still unlocked!

- alias: Laundry door is unlocked
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '23:59:00'
  condition:
  - condition: state
    entity_id: lock.laundry_deadbolt_locked
    state: unlocked
  action:
  - service: media_player.alexa_tts
    data:
      entity_id: group.amazon_echos
      message: Warning, the laundry room door is still unlocked!
  - service: notify.living_room_tv
    data:
      message: Warning, the laundry room door is still unlocked!
