- alias: notify via telegram on Home Assistant start
  initial_state: true
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.telegram_tom
    data:
      message: Home Assistant booted

- alias: 'Telegram callback to remove keyboard'
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/removekeyboard'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'OK'
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      inline_keyboard: []

- alias: 'Telegram callback to display menu'
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/menu'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Menu
      data:
        inline_keyboard:
          - 'Arm Away:/arm_away, Arm Home:/arm_home, Disarm:/disarm'
          - 'Cancel:/removekeyboard'

- alias: Telegram Test
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/test'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: "{{ trigger.event.data.user_id }}"
        message: 'Test message received.'

- alias: 'send Telegram info message'
  initial_state: true
  hide_entity: true
  trigger:
    platform: mqtt
    topic: home/notification/info
  action:
    - service: notify.telegram_tom
      data_template:
        message: '{{ trigger.payload }}'
