# the following are now handled automatically by the hass ios app?
#- platform: ios
#  name: toms_iphone
#  target: !secret toms_notify_target
#
#- platform: ios
#  name: mitzis_iphone
#  target: !secret mitzis_notify_target

- platform: telegram
  name: telegram
  chat_id: !secret telegram_tom

- platform: telegram
  name: telegram_tom
  chat_id: !secret telegram_tom

- platform: telegram
  name: telegram_mitzi
  chat_id: !secret telegram_mitzi

- platform: telegram
  name: telegram_group
  chat_id: !secret telegram_group

- platform: webostv
  host: 192.168.2.20
  name: living_room_tv
  filename: webostv.conf

- platform: alexa_media
  name: alexa_media
